### ISSUE TITLE
remove `findWithAttr` and replace with `indexOf`/`splice`

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/tunely-angular#3]
Change in sprint3.md and solutions

Pass in `album` object instead of `id` for easy searching:

``` js
var index = vm.albums.indexOf(album);
vm.albums.splice(index,1)
```

**Comment by jlopker** [comment]
the problem with this is that angular adds a `$$hash` attribute to objects so the objects. so when the "clean" object is compared with the angularized one, it comes up with nothing.

**Comment by nathanallen** [comment]
This works because objects are reference types. If angular is doing any object _cloning_ in the view, that's another story, but I believe it's just adding attributes to the original object.

See also: http://stackoverflow.com/a/14250677
